export const LOCALSTORAGE_APPLICATION_BASE_KEY = '@chat-application-web'
export const USER_LOCALSTORAGE_KEY = `${LOCALSTORAGE_APPLICATION_BASE_KEY}/user`;
export const AUTH_TOKEN_LOCALSTORAGE_KEY = `${LOCALSTORAGE_APPLICATION_BASE_KEY}/auth_tokens`